# Site settings
title: 4100ESi Site
email: your-email@domain.com
description: Simplax Document Library
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://simplex-fire.com/en/us/DocumentsandMedia/" # the base hostname & protocol for your site
# only use suffix if you need to force index.html to display
suffix: index.html
# host: 127.0.0.1
# theme_file: theme-blue.css

# Build settings
markdown: kramdown
